feat(ci): deploys the worker when the CI pipeline succeeds

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,8 @@
-name: CI Pipeline
+name: CI/CD Pipeline
 
 on:
   push:
+  pull_request:
 
 jobs:
   ci-worker:
@@ -41,3 +42,60 @@ jobs:
 
       - name: Terraform Validate
         run: terraform validate -no-color
+
+  cd-worker:
+    needs: [ci-worker, ci-infra]
+    if: github.ref == 'refs/heads/main'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Deploy to Cloudflare Edge
+        env:
+          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
+          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+        run: |
+          cat <<EOF > metadata.json
+          {
+            "main_module": "worker.js",
+            "bindings": [
+              {
+                "type": "plain_text",
+                "name": "REGISTRY_BASE_URL",
+                "text": "https://apt.fury.io"
+              }
+            ]
+          }
+          EOF
+
+          HTTP_STATUS=$(curl -s -o response.json -w "%{http_code}" -X PUT \
+            "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/scripts/furyous-worker" \
+            -H "Authorization: Bearer $CF_API_TOKEN" \
+            -F "metadata=@metadata.json;type=application/json" \
+            -F "worker.js=@src/worker.js;type=application/javascript+module")
+
+          if [ "$HTTP_STATUS" -eq 200 ]; then
+            echo "✅ Worker successfully deployed to Cloudflare!"
+          else
+            echo "❌ Deployment failed with HTTP $HTTP_STATUS"
+            cat response.json
+            exit 1
+          fi
+
+  cd-worker-cache:
+    if: github.ref == 'refs/heads/main'
+    runs-on: ubuntu-latest
+    needs: cd-worker
+    steps:
+        - name: Purges cloudflare cache
+          env:
+            CF_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
+            CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+          run: |
+            curl -X POST \
+              "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" \
+              -H 'content-type: application/json' \
+              -H "Authorization: bearer $CF_API_TOKEN" \
+              -d '{"hosts": ["furyous.vncsmyrnk.dev"]}' \
+              --fail
